# backend/security/pqc_encryption.py
# Implements post-quantum cryptographic functions using CRYSTALS-Kyber.

import logging
from typing import Tuple

try:
    import oqs
except (ImportError, RuntimeError) as e:
    logging.getLogger(__name__).warning(f"oqs library not available: {e}. PQC features will be disabled.")
    oqs = None

logger = logging.getLogger(__name__)

# Define the Key Encapsulation Mechanism (KEM) we will use
# Kyber is a lattice-based KEM standardized by NIST.
KEM_ALG = "Kyber768"

class PQCCipher:
    """
    Provides methods for Post-Quantum Cryptography using a Key Encapsulation Mechanism (KEM).
    This allows two parties to establish a shared secret over an insecure channel.
    """
    def __init__(self):
        if oqs is None:
            logger.warning("Mock PQCCipher: oqs library not available. PQC is disabled for this session.")
            self._kem = None
            return
        
        try:
            # Check if the chosen KEM algorithm is supported by the OQS library
            self._kem = oqs.KeyEncapsulation(KEM_ALG)
            logger.info(f"PQCCipher initialized with KEM algorithm: {KEM_ALG}")
        except Exception as e:
            logger.error(f"Failed to initialize PQC cipher: {e}")
            self._kem = None

    def generate_keypair(self) -> Tuple[bytes, bytes]:
        """
        Generates a new PQC public and secret key pair.
        
        Returns:
            A tuple containing (public_key, secret_key).
        """
        if self._kem is None:
            return b"mock_public_key", b"mock_secret_key"
        
        public_key = self._kem.generate_keypair()
        secret_key = self._kem.export_secret_key()
        logger.debug("Generated a new PQC key pair.")
        return public_key, secret_key

    def encapsulate_secret(self, public_key: bytes) -> Tuple[bytes, bytes]:
        """
        Generates a shared secret and a ciphertext to send to the key owner.
        This is called by the party that *wants to send* an encrypted message.

        Args:
            public_key: The recipient's public key.

        Returns:
            A tuple containing (ciphertext, shared_secret).
            The ciphertext should be sent to the recipient.
            The shared_secret should be used to encrypt the actual message.
        """
        if self._kem is None:
            return b"mock_ciphertext", b"mock_shared_secret"
        
        logger.debug("Encapsulating a new shared secret.")
        ciphertext, shared_secret = self._kem.encapsulate(public_key)
        return ciphertext, shared_secret

    def decapsulate_secret(self, ciphertext: bytes, secret_key: bytes) -> bytes:
        """
        Uses a secret key to derive the shared secret from a ciphertext.
        This is called by the party that *receives* the encapsulated secret.

        Args:
            ciphertext: The ciphertext received from the sender.
            secret_key: The recipient's own secret key.

        Returns:
            The shared secret, which will match the one generated by the sender.
        """
        if self._kem is None:
            return b"mock_shared_secret"
        
        logger.debug("Decapsulating a shared secret from ciphertext.")
        shared_secret = self._kem.decapsulate(ciphertext, secret_key)
        return shared_secret

# Global instance for easy access
pqc_encryptor = PQCCipher()