apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-core-cloudrun
spec:
  template:
    spec:
      containers:
      - image: ai-core:latest
        env:
        - name: ENVIRONMENT
          value: "production"
        ports:
        - containerPort: 8000
